#!/bin/sh

if ! type "nvcc" > /dev/null; then
  # install foobar here
  echo "No NVCC (NVIDIA CUDA Compiler) detected"
  echo "Using this command ''sudo apt install nvidia-cuda-toolkit'' to install it. Or see https://developer.nvidia.com/Cuda-downloads"
fi


#download 15 trained models
echo "Downing 15 trained models..."
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=16fKEBsuwIYf-IVC_knxards9Yb38-FVN' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=16fKEBsuwIYf-IVC_knxards9Yb38-FVN" -O ./models/model_HOCK.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1zOsvPHB4WN_pB_DjXu-JDHOeMNNKQ-Xg' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1zOsvPHB4WN_pB_DjXu-JDHOeMNNKQ-Xg" -O ./models/model_Higgs.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=12gvNWMXQG5fuaVfnkr9N23d-CVFWRm8i' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=12gvNWMXQG5fuaVfnkr9N23d-CVFWRm8i" -O ./models/model_SUSY.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1Z04IvVIIZdjUGZGIf4CpUQ2Ll06JVVll' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1Z04IvVIIZdjUGZGIf4CpUQ2Ll06JVVll" -O ./models/model_SVHN.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1NupB35Yta_yQFPBHO9AQGBRwjCah_Y0N' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1NupB35Yta_yQFPBHO9AQGBRwjCah_Y0N" -O ./models/model_allstate.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1_twsuE9l9ho9xN16XVd7zG0PJR07yeUX' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1_twsuE9l9ho9xN16XVd7zG0PJR07yeUX" -O ./models/model_cifar10.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=19Pq9JdRFfBr0vF5DW4-YLBq8KC2oEQlW' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=19Pq9JdRFfBr0vF5DW4-YLBq8KC2oEQlW" -O ./models/model_covtype.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1TY9ulqaddU8uw7MTPNRP_2bA9ZOVqQ2Y' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1TY9ulqaddU8uw7MTPNRP_2bA9ZOVqQ2Y" -O ./models/model_cup98.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1icYlxouw6CF1EmZzCOEyWZVVega72Uiz' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1icYlxouw6CF1EmZzCOEyWZVVega72Uiz" -O ./models/model_gisette.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1BU1NgxZFITg5OZnCJ_-KNnts41Zy_KNs' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1BU1NgxZFITg5OZnCJ_-KNnts41Zy_KNs" -O ./models/model_year.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=12jYu7Bf6flPNouS2n1x3awxYnx7Epb4D' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=12jYu7Bf6flPNouS2n1x3awxYnx7Epb4D" -O ./models/model_hepmass.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1G7pBL0PKhCkTPoMpSgTPeDw_gxSDWbdD' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1G7pBL0PKhCkTPoMpSgTPeDw_gxSDWbdD" -O ./models/model_ijcnn1.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1vVLsClSbWlmuAwrO-agtX4KNnLEaCgHj' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1vVLsClSbWlmuAwrO-agtX4KNnLEaCgHj" -O ./models/model_phishing.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1fSMkxImiuSBKQJAOYJNpuFE_UqgjLixB' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1fSMkxImiuSBKQJAOYJNpuFE_UqgjLixB" -O ./models/model_aloi.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1wgSJF7OMyV5vPx8wi4U2PKUPU-ppU5gR' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1wgSJF7OMyV5vPx8wi4U2PKUPU-ppU5gR" -O ./models/model_letter.txt && rm -rf /tmp/cookies.txt


#download 15 data set
echo "Downing 15 data set..."
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1GDVuMCK4-SqiQeXXuVEHYLCCGCvllOrj' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1GDVuMCK4-SqiQeXXuVEHYLCCGCvllOrj" -O ./data/data_HOCK.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1GV7HIDoon2kFifiqDK5wLAlljXRm3BgD' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1GV7HIDoon2kFifiqDK5wLAlljXRm3BgD" -O ./data/data_Higgs.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1Z1xwnilQB7ae7U4U-y_Fn1HkdEH5Lgqr' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1Z1xwnilQB7ae7U4U-y_Fn1HkdEH5Lgqr" -O ./data/data_SUSY.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1sqnuc8O9c58qphMHYIaNZSiHdDKV0AMF' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1sqnuc8O9c58qphMHYIaNZSiHdDKV0AMF" -O ./data/data_SVHN.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=14XjT3mMNvEF5TudSxirArLwzrTth5Ww-' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=14XjT3mMNvEF5TudSxirArLwzrTth5Ww-" -O ./data/data_allstate.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1gIaSFXifC7Y3YAXq4WH8nsLI1fDJdnE8' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1gIaSFXifC7Y3YAXq4WH8nsLI1fDJdnE8" -O ./data/data_cifar10.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1glnrV8_jS1WHRtVHw68_pHi1s2zzSIvg' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1glnrV8_jS1WHRtVHw68_pHi1s2zzSIvg" -O ./data/data_covtype.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1BirJHlIJLw7ozvRcTtjVSXbc6jzcOEI4' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1BirJHlIJLw7ozvRcTtjVSXbc6jzcOEI4" -O ./data/data_cup98.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1ymnr3Zy4cFFjzXFRZrBhRi4vEXlwu3tT' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1ymnr3Zy4cFFjzXFRZrBhRi4vEXlwu3tT" -O ./data/data_gisette.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1r4wpnbSC694mH-MxUlabwPSOdJNUXsDe' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1r4wpnbSC694mH-MxUlabwPSOdJNUXsDe" -O ./data/data_year.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=175RNWaO7Gw1aWNO6B_PqYSh8YruaeDDl' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=175RNWaO7Gw1aWNO6B_PqYSh8YruaeDDl" -O ./data/data_hepmass.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1NuHfkwK2BssSUXhVAWlzcSlM7FVFEVNm' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1NuHfkwK2BssSUXhVAWlzcSlM7FVFEVNm" -O ./data/data_ijcnn1.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=19iHQ5EvFiQ1eZfopWopcFje1vpBuYolI' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=19iHQ5EvFiQ1eZfopWopcFje1vpBuYolI" -O ./data/data_phishing.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1uFsmLYPc26QxvTKS8bu0_85sl9AMtzVb' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1uFsmLYPc26QxvTKS8bu0_85sl9AMtzVb" -O ./data/data_aloi.txt && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1ntVI6ZczWKpleP9Q5GELA2j_GptX1dBk' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1ntVI6ZczWKpleP9Q5GELA2j_GptX1dBk" -O ./data/data_letter.txt && rm -rf /tmp/cookies.txt

#compile the Tahoe
make;

#run 15 examples
./Tahoe ./models/model_HOCK.txt ./data/data_HOCK.txt;
./Tahoe ./models/model_Higgs.txt ./data/data_Higgs.txt;
./Tahoe ./models/model_SUSY.txt ./data/data_SUSY.txt;
./Tahoe ./models/model_SVHN.txt ./data/data_SVHN.txt;
./Tahoe ./models/model_allstate.txt ./data/data_allstate.txt;
./Tahoe ./models/model_cifar10.txt ./data/data_cifar10.txt;
./Tahoe ./models/model_covtype.txt ./data/data_covtype.txt;
./Tahoe ./models/model_cup98.txt ./data/data_cup98.txt;
./Tahoe ./models/model_gisette.txt ./data/data_gisette.txt;
./Tahoe ./models/model_year.txt ./data/data_year.txt;
./Tahoe ./models/model_hepmass.txt ./data/data_hepmass.txt;
./Tahoe ./models/model_ijcnn1.txt ./data/data_ijcnn1.txt;
./Tahoe ./models/model_phishing.txt ./data/data_phishing.txt;
./Tahoe ./models/model_aloi.txt ./data/data_aloi.txt;
./Tahoe ./models/model_letter.txt ./data/data_letter.txt;